Match protocol relative URLs (`://`)
robinst/linkify pull request #17
Opened 2021-03-01 23:26 UTC by mre

Protocol-relative links (PRL), also known as protocol-relative URLs (PRURL), are URLs that have no protocol specified. For example, `//example.com` will use the protocol of the current page, typically HTTP or HTTPS.

These URLs commonly occur in the wild, specifically on pages that support both HTTP and HTTPS protocols.

Since the URLs without a protocol belong to the class of relative URLs, it is up to the user to decide what protocol to use when parsing these URLs.
Example configuration for the url crate: https://docs.rs/url/2.2.1/url/#base-url

It would be great to support those in linkify, as I discovered quite a few cases while working on recursion in lychee.
(https://github.com/lycheeverse/lychee/pull/165)

2021-03-02 00:14 UTC, robinst commented
Hmm, so this PR adds support for `://example.org`, but if I understand you correctly, you actually want `//example.org`, no?

If we want to support `/`, we need to trigger on `/` as well, not only on `:`.

2021-03-02 14:18 UTC, mre commented
Oh, you're right. That's wrong. It was a bit late.

2021-03-02 14:50 UTC, mre commented on src/url.rs
> +            _ => ("://", 3),
If you like, we can make the trigger an `enum` type. Then we can use an exhaustive match here:

```rust
let (proto, offset) = match self.trigger {
  Trigger::Slash => ("//", 2),
  Trigger::Colon => ("://", 3),
}
```

2021-03-02 15:02 UTC, mre commented on src/url.rs
> +            _ => ("://", 3),
Ah I just went ahead and added it. Think that's cleaner now. Let me know if I should revert the change. ✌️

2021-03-02 15:02 UTC, mre commented
Should be fixed now.

2021-03-04 04:34 UTC, robinst requested changes

2021-03-04 04:34 UTC, robinst commented on src/finder.rs
> +pub enum Trigger {
Can you make this `pub(crate)`? Want to make it clear at this point that it's not part of the API.

2021-03-04 04:34 UTC, robinst commented on src/url.rs
> +        if s.is_empty() && self.trigger == Trigger::Slash {
Hmm does this mean in `abc //example.org` we wouldn't match `//example.org`? Can you add a test case for this?

Also needs some more negative test cases, e.g. something like `foo//bar` should *not* match, but e.g. `"//foo.bar` should.

2021-03-04 04:34 UTC, robinst commented on src/finder.rs
>      fn new(text: &'t str, url: bool, email: bool, email_domain_must_have_dot: bool) -> Links<'t> {
I think we should have an option (disabled by default) for the new functionality, something like `protocol_relative_urls(true)`. Normally I wouldn't want to match those kinds of links in plain text.

You can see e.g. GitHub not matching it either: //github.com

2022-04-14 10:23 UTC, robinst commented
Just checking back on this one. Still needs some more changes (and resolving conflicts).

2022-04-14 14:39 UTC, mre commented
Oh yeah. Didn't find the time to look into it, heh. Will set myself a reminder for next week.

2022-07-11 11:13 UTC, mre commented
Should we close this and try again at a later point in time? linkify 0.9.0 made some changes to the codebase, so it's probably easier to start from a clean slate.

2022-07-11 13:21 UTC, robinst commented
Yep! It should be much simpler to do that now as the necessary bits of logic are now separate from `UrlScanner`!

2022-07-11 13:21 UTC, closed without merging